MCHS_PKG_HOMEPAGE=https://github.com/google/googletest
MCHS_PKG_DESCRIPTION="Google C++ testing framework"
MCHS_PKG_LICENSE="BSD 3-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.11.0
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/google/googletest/archive/release-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_AUTO_UPDATE_TAG_REGEXP="\d+\.\d+\.\d+"
MCHS_PKG_DEPENDS="libc++"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"

