MCHS_PKG_HOMEPAGE=http://www.muchsync.org/
MCHS_PKG_DESCRIPTION="Synchronize notmuch mail across machines"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=6
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=http://www.muchsync.org/src/muchsync-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=0b3de3b4d885edb9f887a07dcbc8b596e7fef2038c61e682cfa55a13fa4ce9e8
MCHS_PKG_DEPENDS="libc++, libsqlite, libxapian, notmuch, openssl"
