MCHS_PKG_HOMEPAGE=https://github.com/martinh/libconfuse
MCHS_PKG_DESCRIPTION="Small configuration file parser library for C"
MCHS_PKG_LICENSE="LGPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=3.3
MCHS_PKG_SRCURL=https://github.com/martinh/libconfuse/releases/download/v$MCHS_PKG_VERSION/confuse-$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=3a59ded20bc652eaa8e6261ab46f7e483bc13dad79263c15af42ecbb329707b8
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_BREAKS="libconfuse-dev"
MCHS_PKG_REPLACES="libconfuse-dev"
