MCHS_PKG_HOMEPAGE=http://ipmitool.sourceforge.net
MCHS_PKG_DESCRIPTION="Command-line interface to IPMI-enabled devices"
MCHS_PKG_LICENSE="BSD"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.8.18
MCHS_PKG_REVISION=7
MCHS_PKG_SRCURL=http://downloads.sourceforge.net/project/ipmitool/ipmitool/$MCHS_PKG_VERSION/ipmitool-$MCHS_PKG_VERSION.tar.bz2
MCHS_PKG_SHA256=0c1ba3b1555edefb7c32ae8cd6a3e04322056bc087918f07189eeedfc8b81e01
MCHS_PKG_DEPENDS="ncurses, openssl, readline"
