MCHS_PKG_HOMEPAGE=https://fmt.dev/latest/index.html
MCHS_PKG_DESCRIPTION="Open-source formatting library for C++"
MCHS_PKG_LICENSE="BSD"
MCHS_PKG_LICENSE_FILE="LICENSE.rst"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=8.1.1
MCHS_PKG_SRCURL=https://github.com/fmtlib/fmt/archive/$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=3d794d3cf67633b34b2771eb9f073bde87e846e0d395d254df7b211ef1ec7346
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_EXTRA_CONFIGURE_ARGS="-DFMT_TEST=OFF"
MCHS_PKG_NO_STATICSPLIT=true
