MCHS_PKG_HOMEPAGE=https://github.com/gabime/spdlog
MCHS_PKG_DESCRIPTION="Very fast, header-only/compiled, C++ logging library"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.9.2
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/gabime/spdlog/archive/refs/tags/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=6fff9215f5cb81760be4cc16d033526d1080427d236e86d70bb02994f85e3d38
MCHS_PKG_DEPENDS="libc++"
MCHS_PKG_BUILD_DEPENDS="fmt"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DSPDLOG_BUILD_SHARED=ON
-DSPDLOG_FMT_EXTERNAL=ON
"
