MCHS_PKG_HOMEPAGE=https://github.com/mapbox/protozero
MCHS_PKG_DESCRIPTION="Minimalistic protocol buffer decoder and encoder in C++"
MCHS_PKG_LICENSE="BSD 2-Clause"
MCHS_PKG_LICENSE_FILE="LICENSE.md"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.7.0
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/mapbox/protozero/archive/v${MCHS_PKG_VERSION}.zip
MCHS_PKG_SHA256=b1dc381cdf75bc6531f1fee13c76a72bae432660984b3316f104c74c355766fd
MCHS_PKG_GROUPS="science"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="-DPYBIND11_FINDPYTHON=OFF"
