MCHS_PKG_HOMEPAGE=https://xiph.org/vorbis/
MCHS_PKG_DESCRIPTION="Library for using the Ogg Vorbis compressed audio format"
MCHS_PKG_LICENSE="BSD 3-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.3.7
MCHS_PKG_SRCURL=http://downloads.xiph.org/releases/vorbis/libvorbis-${MCHS_PKG_VERSION}.tar.xz
MCHS_PKG_SHA256=b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b
MCHS_PKG_DEPENDS="libogg"
MCHS_PKG_BREAKS="libvorbis-dev"
MCHS_PKG_REPLACES="libvorbis-dev"
