MCHS_PKG_HOMEPAGE=https://www.colm.net/open-source/ragel/
MCHS_PKG_DESCRIPTION="Compiles finite state machines from regular languages into executable C, C++, Objective-C, or D code"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=6.10
MCHS_PKG_REVISION=3
MCHS_PKG_SRCURL=https://www.colm.net/files/ragel/ragel-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=5f156edb65d20b856d638dd9ee2dfb43285914d9aa2b6ec779dac0270cd56c3f
MCHS_PKG_DEPENDS="libc++"
