MCHS_PKG_HOMEPAGE=https://www.opus-codec.org/
MCHS_PKG_DESCRIPTION="Utilities to encode and decode .opus files"
MCHS_PKG_LICENSE="BSD 3-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.2
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=http://downloads.xiph.org/releases/opus/opus-tools-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=b4e56cb00d3e509acfba9a9b627ffd8273b876b4e2408642259f6da28fa0ff86
MCHS_PKG_DEPENDS="libopusenc, libogg, libflac, opusfile, libopus"
