MCHS_PKG_HOMEPAGE=https://github.com/troglobit/redir
MCHS_PKG_DESCRIPTION="TCP port redirector for UNIX"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=3.3
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/troglobit/redir/releases/download/v$MCHS_PKG_VERSION/redir-$MCHS_PKG_VERSION.tar.xz
MCHS_PKG_SHA256=7ce53ac52a24c1b3279b994bfffbd429c44df2db10a4b1a0f54e108604fdae6e
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_RM_AFTER_INSTALL="share/applications share/pixmaps"
