MCHS_PKG_HOMEPAGE=https://github.com/KhronosGroup/OpenCL-CLHPP
MCHS_PKG_DESCRIPTION="Khronos OpenCL C++ Headers"
MCHS_PKG_LICENSE="Apache-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=2.0.16
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/KhronosGroup/OpenCL-CLHPP/archive/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=869456032e60787eed9fceaeaf6c6cb4452bc0ff97e0f5a271510145a1c8f4d4
MCHS_PKG_PLATFORM_INDEPENDENT=true
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTS=OFF
"
