MCHS_PKG_HOMEPAGE=https://libevent.org/
MCHS_PKG_DESCRIPTION="Library that provides asynchronous event notification"
MCHS_PKG_LICENSE="BSD 3-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=2.1.12
MCHS_PKG_SRCURL=https://github.com/libevent/libevent/archive/release-${MCHS_PKG_VERSION}-stable.tar.gz
MCHS_PKG_SHA256=7180a979aaa7000e1264da484f712d403fcf7679b1e9212c4e3d09f5c93efc24
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_AUTO_UPDATE_TAG_REGEXP="\d+\.\d+\.\d+"
MCHS_PKG_BREAKS="libevent-dev"
MCHS_PKG_REPLACES="libevent-dev"
MCHS_PKG_RM_AFTER_INSTALL="bin/event_rpcgen.py"

MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DEVENT__BUILD_SHARED_LIBRARIES=ON
-DEVENT__DISABLE_BENCHMARK=ON
-DEVENT__DISABLE_OPENSSL=ON
-DEVENT__DISABLE_REGRESS=ON
-DEVENT__DISABLE_SAMPLES=ON
-DEVENT__DISABLE_TESTS=ON
-DEVENT__DISABLE_TESTS=ON
-DEVENT__HAVE_WAITPID_WITH_WNOWAIT=ON
-DEVENT__SIZEOF_PTHREAD_T=$((MCHS_ARCH_BITS/8))
"
