MCHS_PKG_HOMEPAGE=https://tox.chat
MCHS_PKG_DESCRIPTION="Backend library for the Tox protocol"
MCHS_PKG_LICENSE="GPL-3.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.2.15
MCHS_PKG_SRCURL=https://github.com/TokTok/toxcore/archive/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=577e23fe52f8be6739a9fffb2b16bfefd3a0ef4994d0714cb28a1ecca3669ca6
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_DEPENDS="libsodium"
MCHS_PKG_BREAKS="c-toxcore-dev"
MCHS_PKG_REPLACES="c-toxcore-dev"
#MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DBOOTSTRAP_DAEMON=off
-DDHT_BOOTSTRAP=off
-DBUILD_TOXAV=off
-DBUILD_AV_TEST=off
"
