MCHS_PKG_HOMEPAGE=https://sourceforge.net/projects/gnuski
MCHS_PKG_DESCRIPTION="Open source clone of Skifree, the old Windows game"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="Henrik Grimler @Grimler91"
MCHS_PKG_VERSION=0.3
MCHS_PKG_REVISION=6
MCHS_PKG_SRCURL=https://sourceforge.net/projects/gnuski/files/gnuski/gnuski-${MCHS_PKG_VERSION}/gnuski-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=1b629bd29dd6ad362b56055ccdb4c7ad462ff39d7a0deb915753c2096f5f959d
MCHS_PKG_DEPENDS="ncurses"
MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_GROUPS="games"
