MCHS_PKG_HOMEPAGE=https://github.com/google/flatbuffers
MCHS_PKG_DESCRIPTION="Memory Efficient Serialization Library"
MCHS_PKG_LICENSE="Apache-2.0"
MCHS_PKG_MAINTAINER="Simeon Huang <symeon@librehat.com>"
MCHS_PKG_VERSION=2.0.0
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/google/flatbuffers/archive/refs/tags/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=9ddb9031798f4f8754d00fca2f1a68ecf9d0f83dfac7239af1311e4fd9a565c4
MCHS_PKG_AUTO_UPDATE=true

MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DFLATBUFFERS_BUILD_SHAREDLIB=ON
-DFLATBUFFERS_BUILD_TESTS=OFF
"
