MCHS_PKG_HOMEPAGE=https://github.com/Tencent/rapidjson/
MCHS_PKG_DESCRIPTION="fast JSON parser/generator for C++ with SAX/DOM style API"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.1.0
MCHS_PKG_REVISION=4
MCHS_PKG_SRCURL=https://github.com/Tencent/rapidjson/archive/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e
MCHS_PKG_EXTRA_CONFIGURE_ARGS="-DRAPIDJSON_BUILD_EXAMPLES=OFF"
