MCHS_PKG_HOMEPAGE=https://www.gnu.org/software/automake/
MCHS_PKG_DESCRIPTION="Tool for automatically generating Makefile.in files"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.16.5
MCHS_PKG_SRCURL=https://mirrors.kernel.org/gnu/automake/automake-${MCHS_PKG_VERSION}.tar.xz
MCHS_PKG_SHA256=f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469
MCHS_PKG_DEPENDS="autoconf"
MCHS_PKG_PLATFORM_INDEPENDENT=true
MCHS_PKG_GROUPS="base-devel"
