MCHS_PKG_HOMEPAGE=https://gitlab.com/ecodis/exhale
MCHS_PKG_DESCRIPTION="Open source xHE-AAC encoder"
MCHS_PKG_LICENSE="custom"
MCHS_PKG_LICENSE_FILE="include/License.htm"
MCHS_PKG_MAINTAINER="@DLC01"
MCHS_PKG_VERSION=1.1.9
MCHS_PKG_SRCURL=https://gitlab.com/ecodis/exhale/-/archive/v${MCHS_PKG_VERSION}/exhale-v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=21a19f166a9b77731cbce8af2068ad2a5be2745b9987980fe2f9e371aaa738ac
MCHS_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
