MCHS_PKG_HOMEPAGE=https://gstreamer.freedesktop.org/
MCHS_PKG_DESCRIPTION="GStreamer Bad Plug-ins"
MCHS_PKG_LICENSE="LGPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.19.3
MCHS_PKG_SRCURL=https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-${MCHS_PKG_VERSION}.tar.xz
MCHS_PKG_SHA256=50193a23b13713ccb32ee5d1852faeeaed29b91f8398285acdfd522fa3e16835
MCHS_PKG_DEPENDS="gst-plugins-base, libbz2, libcurl, libiconv, libpng, librsvg, libssh2, libsndfile, libx264, libx265, littlecms, openal-soft, openjpeg"
MCHS_PKG_BREAKS="gst-plugins-bad-dev"
MCHS_PKG_REPLACES="gst-plugins-bad-dev"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-Dandroidmedia=disabled
-Dexamples=disabled
-Drtmp=disabled
-Dtests=disabled
-Dzbar=disabled
-Dwebp=disabled
-Dvulkan=disabled
-Dhls-crypto=openssl
"
