MCHS_PKG_HOMEPAGE=https://github.com/mchs/libandroid-shmem
MCHS_PKG_DESCRIPTION="System V shared memory emulation on Android using ashmem"
MCHS_PKG_LICENSE="BSD 3-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.3
MCHS_PKG_SRCURL=https://github.com/mchs/libandroid-shmem/archive/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=8d161993260d7bd4f35956c5a302a1edd9fe5b9fd1a239d8e721b2746ab0920d
MCHS_PKG_BREAKS="libandroid-shmem-dev"
MCHS_PKG_REPLACES="libandroid-shmem-dev"
MCHS_PKG_BUILD_IN_SRC=true
