MCHS_PKG_HOMEPAGE=https://www.gnupg.org/related_software/pinentry/index.html
MCHS_PKG_DESCRIPTION="Dialog allowing secure password entry"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.2.0
MCHS_PKG_SRCURL=https://www.gnupg.org/ftp/gcrypt/pinentry/pinentry-$MCHS_PKG_VERSION.tar.bz2
MCHS_PKG_SHA256=10072045a3e043d0581f91cd5676fcac7ffee957a16636adedaa4f583a616470
MCHS_PKG_DEPENDS="libandroid-support, libassuan, libiconv, ncurses"
MCHS_PKG_BUILD_DEPENDS="libgpg-error"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="--disable-pinentry-fltk --without-libcap"
