MCHS_PKG_HOMEPAGE=https://www.gnu.org/software/ocrad/ocrad.html
MCHS_PKG_DESCRIPTION="Optical Character Recognition program based on a feature extraction method"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.27
MCHS_PKG_REVISION=3
MCHS_PKG_SRCURL=https://mirrors.kernel.org/gnu/ocrad/ocrad-${MCHS_PKG_VERSION}.tar.lz
MCHS_PKG_SHA256=a9bfe67e9a040907aff5640dca56392476b6a89e48e37dc94ba846c5b6733b36
MCHS_PKG_DEPENDS="libc++"
MCHS_PKG_BREAKS="ocrad-dev"
MCHS_PKG_REPLACES="ocrad-dev"
