MCHS_PKG_HOMEPAGE=https://github.com/tree-sitter/tree-sitter
MCHS_PKG_DESCRIPTION="An incremental parsing system for programming tools"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.20.4
MCHS_PKG_SRCURL=https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=979ad0b36eb90975baf0c65d155d106276cac08afb1c2fe0ad54d4b7d498ce39
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_BUILD_IN_SRC=true
