MCHS_PKG_HOMEPAGE=https://www.gnupg.org/related_software/npth/
MCHS_PKG_DESCRIPTION="New GNU Portable Threads Library"
MCHS_PKG_LICENSE="LGPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.6
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://www.gnupg.org/ftp/gcrypt/npth/npth-${MCHS_PKG_VERSION}.tar.bz2
MCHS_PKG_SHA256=1393abd9adcf0762d34798dc34fdcf4d0d22a8410721e76f1e3afcd1daa4e2d1
MCHS_PKG_BREAKS="libnpth-dev"
MCHS_PKG_REPLACES="libnpth-dev"
