MCHS_PKG_HOMEPAGE=https://libisl.sourceforge.io/
MCHS_PKG_DESCRIPTION="Library for manipulating sets and relations of integer points bounded by linear constraints"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.24
MCHS_PKG_SRCURL=http://archive.ubuntu.com/ubuntu/pool/main/i/isl/isl_${MCHS_PKG_VERSION}.orig.tar.xz
MCHS_PKG_SHA256=043105cc544f416b48736fff8caf077fb0663a717d06b1113f16e391ac99ebad
MCHS_PKG_DEPENDS="libgmp"
MCHS_PKG_BREAKS="libisl-dev"
MCHS_PKG_REPLACES="libisl-dev"
