MCHS_PKG_HOMEPAGE=https://github.com/jhawthorn/fzy
MCHS_PKG_DESCRIPTION="A simple, fast fuzzy finder for the terminal"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="Krishna Kanhaiya @kcubeterm"
MCHS_PKG_VERSION=1.0
MCHS_PKG_SRCURL=https://github.com/jhawthorn/fzy/archive/${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=80257fd74579e13438b05edf50dcdc8cf0cdb1870b4a2bc5967bd1fdbed1facf
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_BUILD_IN_SRC=true
