MCHS_PKG_HOMEPAGE=https://github.com/dylanaraps/neofetch
MCHS_PKG_DESCRIPTION="Simple system information script"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=7.1.0
MCHS_PKG_SRCURL=https://github.com/dylanaraps/neofetch/archive/${MCHS_PKG_VERSION}/neofetch-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_DEPENDS="bash"
MCHS_PKG_EXTRA_MAKE_ARGS="PREFIX=$MCHS_PREFIX SYSCONFDIR=$MCHS_PREFIX/etc"
MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_PLATFORM_INDEPENDENT=true
