MCHS_PKG_HOMEPAGE=https://www.libssh.org/
MCHS_PKG_DESCRIPTION="Tiny C SSH library"
MCHS_PKG_LICENSE="LGPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.9.6
MCHS_PKG_SRCURL=https://www.libssh.org/files/${MCHS_PKG_VERSION:0:3}/libssh-$MCHS_PKG_VERSION.tar.xz
MCHS_PKG_SHA256=86bcf885bd9b80466fe0e05453c58b877df61afa8ba947a58c356d7f0fab829b
MCHS_PKG_DEPENDS="openssl, zlib"
MCHS_PKG_BREAKS="libssh-dev"
MCHS_PKG_REPLACES="libssh-dev"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DHAVE_ARGP_H=OFF
-DWITH_GSSAPI=OFF
 "
