MCHS_PKG_HOMEPAGE=https://capnproto.org/
MCHS_PKG_DESCRIPTION="Data interchange format and capability-based RPC system."
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.9.1
MCHS_PKG_REVISION=2
MCHS_PKG_SRCURL=https://capnproto.org/capnproto-c++-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=83680aaef8c192b884e38eab418b8482d321af6ae7ab7befa3a9370b8e716aad
MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_FORCE_CMAKE=true
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
"
