MCHS_PKG_HOMEPAGE=https://github.com/google/leveldb
MCHS_PKG_DESCRIPTION="Fast key-value storage library"
MCHS_PKG_LICENSE="BSD 3-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.23
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/google/leveldb/archive/${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=9a37f8a6174f09bd622bc723b55881dc541cd50747cbd08831c2a82d620f6d76
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_DEPENDS="libc++"
MCHS_PKG_BREAKS="leveldb-dev"
MCHS_PKG_REPLACES="leveldb-dev"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=TRUE
-DLEVELDB_BUILD_TESTS=OFF
-DLEVELDB_BUILD_BENCHMARKS=OFF
"
