MCHS_PKG_HOMEPAGE=https://nlopt.readthedocs.io/
MCHS_PKG_DESCRIPTION="Library for nonlinear optimization"
MCHS_PKG_LICENSE="LGPL-2.1, MIT"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=2.7.0
MCHS_PKG_SRCURL=https://github.com/stevengj/nlopt/archive/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=b881cc2a5face5139f1c5a30caf26b7d3cb43d69d5e423c9d78392f99844499f
MCHS_PKG_DEPENDS="libc++"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DNLOPT_CXX=ON
-DNLOPT_FORTRAN=OFF
-DNLOPT_PYTHON=OFF
-DNLOPT_OCTAVE=OFF
-DNLOPT_MATLAB=OFF
-DNLOPT_GUILE=OFF
-DNLOPT_SWIG=OFF
-DNLOPT_TESTS=OFF
"
