MCHS_PKG_HOMEPAGE=https://github.com/fornwall/utfdecode
MCHS_PKG_DESCRIPTION="Tool for decoding, encoding and debugging unicode"
MCHS_PKG_LICENSE="Apache-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.3.4
MCHS_PKG_REVISION=5
MCHS_PKG_SRCURL=https://github.com/fornwall/utfdecode/releases/download/v$MCHS_PKG_VERSION/utfdecode-$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=5fd1473f6cf6bdedeb33569c3b0f6823aceda366c714f6a475e2d28767f99b5a
MCHS_PKG_AUTO_UPDATE=true
MCHS_PKG_DEPENDS="libc++"
