MCHS_PKG_HOMEPAGE=https://dl.matroska.org/downloads/libmatroska/
MCHS_PKG_DESCRIPTION="Matroska library"
MCHS_PKG_LICENSE="LGPL-2.1"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.6.3
MCHS_PKG_SRCURL=https://github.com/Matroska-Org/libmatroska/archive/release-$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=0c8c875ae26ac69a722f7fd0f4a4fecb4fdff681f2a165f09c06a40cbf1d0de6
MCHS_PKG_DEPENDS=libebml
MCHS_PKG_NO_STATICSPLIT=true
