MCHS_PKG_HOMEPAGE=https://tls.mbed.org/
MCHS_PKG_DESCRIPTION="Light-weight cryptographic and SSL/TLS library"
MCHS_PKG_LICENSE="Apache-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_SRCURL=https://github.com/ARMmbed/mbedtls.git
MCHS_PKG_VERSION=3.0.0
MCHS_PKG_GIT_BRANCH=mbedtls-$MCHS_PKG_VERSION
MCHS_PKG_BREAKS="mbedtls-dev"
MCHS_PKG_REPLACES="mbedtls-dev"

MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_STATIC_MBEDTLS_LIBRARY=OFF
-DUSE_SHARED_MBEDTLS_LIBRARY=ON
-DENABLE_TESTING=OFF
-DENABLE_PROGRAMS=OFF
 "
