MCHS_PKG_HOMEPAGE=http://mp3splt.sourceforge.net
MCHS_PKG_DESCRIPTION="Utility to split MP3, Ogg Vorbis and native FLAC files without decoding"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=0.9.2
MCHS_PKG_REVISION=4
MCHS_PKG_SRCURL=http://prdownloads.sourceforge.net/mp3splt/libmp3splt-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=30eed64fce58cb379b7cc6a0d8e545579cb99d0f0f31eb00b9acc8aaa1b035dc
MCHS_PKG_DEPENDS="libmad, libid3tag, libvorbis, libflac, pcre, libtool"
MCHS_PKG_BREAKS="libmp3splt-dev"
MCHS_PKG_REPLACES="libmp3splt-dev"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="--disable-cutter"
