MCHS_PKG_HOMEPAGE=https://aomedia.org/
MCHS_PKG_DESCRIPTION="AV1 Video Codec Library"
MCHS_PKG_LICENSE="BSD 2-Clause"
MCHS_PKG_LICENSE_FILE="LICENSE, PATENTS"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=3.2.0
MCHS_PKG_SRCURL=https://aomedia.googlesource.com/aom.git
MCHS_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=1"
