MCHS_PKG_HOMEPAGE=https://git.sr.ht/~sircmpwn/scdoc
MCHS_PKG_DESCRIPTION="Small man page generator"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="Yaksh Bariya <yakshbari4@gmail.com>"
MCHS_PKG_VERSION=1.11.2
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://git.sr.ht/~sircmpwn/scdoc/archive/$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=e9ff9981b5854301789a6778ee64ef1f6d1e5f4829a9dd3e58a9a63eacc2e6f0
MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_EXTRA_MAKE_ARGS="OUTDIR=$MCHS_PKG_SRCDIR HOST_SCDOC=$MCHS_PKG_HOSTBUILD_DIR/scdoc"
MCHS_PKG_HOSTBUILD=true

mchs_step_host_build() {
	cd $MCHS_PKG_SRCDIR
	make OUTDIR=$MCHS_PKG_HOSTBUILD_DIR
}
