MCHS_PKG_HOMEPAGE=https://github.com/libnet/libnet
MCHS_PKG_DESCRIPTION="A library which provides API for commonly used low-level net functions"
MCHS_PKG_LICENSE="BSD 2-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.2
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://github.com/libnet/libnet/releases/download/v$MCHS_PKG_VERSION/libnet-$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=caa4868157d9e5f32e9c7eac9461efeff30cb28357f7f6bf07e73933fb4edaa7
MCHS_PKG_AUTO_UPDATE=true
