MCHS_PKG_HOMEPAGE=https://bellard.org/quickjs/
MCHS_PKG_DESCRIPTION="QuickJS is a small and embeddable Javascript engine"
MCHS_PKG_LICENSE="MIT"
MCHS_PKG_MAINTAINER="@mchs"
_YEAR=2021
_MONTH=03
_DAY=27
MCHS_PKG_VERSION=1:${_YEAR}${_MONTH}${_DAY}
MCHS_PKG_REVISION=2
MCHS_PKG_SRCURL=https://bellard.org/quickjs/quickjs-${_YEAR}-${_MONTH}-${_DAY}.tar.xz
MCHS_PKG_SHA256=a45bface4c3379538dea8533878d694e289330488ea7028b105f72572fe7fe1a
MCHS_PKG_BUILD_IN_SRC=true
MCHS_PKG_NO_STATICSPLIT=true
MCHS_PKG_EXTRA_MAKE_ARGS="
CROSS_PREFIX=${MCHS_HOST_PLATFORM}-
CONFIG_CLANG=y
CONFIG_DEFAULT_AR=y
-W run-test262
-W run-test262-bn
prefix=$MCHS_PREFIX
"
