MCHS_PKG_HOMEPAGE=http://ngspice.sourceforge.net/
MCHS_PKG_DESCRIPTION="A mixed-level/mixed-signal circuit simulator"
MCHS_PKG_LICENSE="BSD 3-Clause, LGPL-2.1"
MCHS_PKG_LICENSE_FILE="COPYING"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=35
MCHS_PKG_SRCURL=https://downloads.sourceforge.net/ngspice/ngspice-${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=c1b7f5c276db579acb3f0a7afb64afdeb4362289a6cab502d4ca302d6e5279ec
MCHS_PKG_DEPENDS="libc++"
MCHS_PKG_GROUPS="science"
