MCHS_PKG_HOMEPAGE=https://osmcode.org/osmium-tool/
MCHS_PKG_DESCRIPTION="A multipurpose command line tool based on the Osmium Library"
MCHS_PKG_LICENSE="GPL-3.0"
MCHS_PKG_LICENSE_FILE="LICENSE.txt"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.13.1
MCHS_PKG_REVISION=2
MCHS_PKG_SRCURL=https://github.com/osmcode/osmium-tool/archive/v${MCHS_PKG_VERSION}.tar.gz
MCHS_PKG_SHA256=d6273e2614d390d8444b767018b7023bdac3538cbe094d2799eee50b6f08cd03
MCHS_PKG_DEPENDS="libosmium, libprotozero, boost, libbz2, zlib, liblz4, libexpat"
MCHS_PKG_GROUPS="science"
