MCHS_SUBPKG_DESCRIPTION="Programs for manipulating HEIF (HEIC/AVIF) image files"
MCHS_SUBPKG_INCLUDE="bin/ share/man/man1/"
MCHS_SUBPKG_LICENSE="MIT"
MCHS_SUBPKG_LICENSE_FILE="examples/COPYING"
MCHS_SUBPKG_DEPENDS="libjpeg-turbo, libpng"
