MCHS_PKG_HOMEPAGE=https://www.netfilter.org/projects/libnftnl/
MCHS_PKG_DESCRIPTION="Netfilter library providing interface to the nf_tables subsystem"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.2.0
MCHS_PKG_SRCURL=http://netfilter.org/projects/libnftnl/files/libnftnl-$MCHS_PKG_VERSION.tar.bz2
MCHS_PKG_SHA256=90b01fddfe9be8c3245c3ba5ff5a4424a8df708828f92b2b361976b658c074f5
MCHS_PKG_DEPENDS="libmnl"
MCHS_PKG_BREAKS="libnftnl-dev"
MCHS_PKG_REPLACES="libnftnl-dev"
