MCHS_PKG_HOMEPAGE=https://wiki.gnome.org/Projects/JsonGlib
MCHS_PKG_DESCRIPTION="GLib JSON manipulation library"
MCHS_PKG_LICENSE="GPL-2.0"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=1.6.6
MCHS_PKG_REVISION=2
MCHS_PKG_SRCURL=https://download.gnome.org/sources/json-glib/${MCHS_PKG_VERSION:0:3}/json-glib-${MCHS_PKG_VERSION}.tar.xz
MCHS_PKG_SHA256=96ec98be7a91f6dde33636720e3da2ff6ecbb90e76ccaa49497f31a6855a490e
MCHS_PKG_DEPENDS="glib"
MCHS_PKG_BREAKS="json-glib-dev"
MCHS_PKG_REPLACES="json-glib-dev"
MCHS_PKG_EXTRA_CONFIGURE_ARGS="
-Dintrospection=disabled
-Dgtk_doc=disabled
"
MCHS_PKG_RM_AFTER_INSTALL="
share/installed-tests
libexec/installed-tests
bin/
"
