MCHS_PKG_HOMEPAGE=http://software.schmorp.de/pkg/libev.html
MCHS_PKG_DESCRIPTION="Full-featured and high-performance event loop library"
MCHS_PKG_LICENSE="BSD 2-Clause"
MCHS_PKG_MAINTAINER="@mchs"
MCHS_PKG_VERSION=4.33
MCHS_PKG_REVISION=1
MCHS_PKG_SRCURL=https://fossies.org/linux/misc/libev-$MCHS_PKG_VERSION.tar.gz
MCHS_PKG_SHA256=507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
MCHS_PKG_BREAKS="libev-dev"
MCHS_PKG_REPLACES="libev-dev"
